## Part 1: N維陣列

資料要數值化成Ｎ維陣列  
資料要表格化以幫助理解  
資料要視覺化以幫助理解

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

串列(list)與陣列(array)的項目皆有序可從0開始索引  
串列的項目可以不同類別  
陣列的項目必須相同類別，儲存在一段連續記憶體，故運算效率高

In [0]:
a = [5, 5, 6, 6]
b = [a, a]
c = [b, b, b, b, b]
c

[[[5, 5, 6, 6], [5, 5, 6, 6]],
 [[5, 5, 6, 6], [5, 5, 6, 6]],
 [[5, 5, 6, 6], [5, 5, 6, 6]],
 [[5, 5, 6, 6], [5, 5, 6, 6]],
 [[5, 5, 6, 6], [5, 5, 6, 6]]]

只有cell最後一行的值會自動傳入print

In [0]:
print(type(c))
print(len(c))
print(len(c[0]))
print(len(c[0][0]))

<class 'list'>
5
2
4


用項目皆為數值的串列產生陣列  
陣列 = np.array(串列)

In [0]:
arr = np.array(c)
arr

array([[[5, 5, 6, 6],
        [5, 5, 6, 6]],

       [[5, 5, 6, 6],
        [5, 5, 6, 6]],

       [[5, 5, 6, 6],
        [5, 5, 6, 6]],

       [[5, 5, 6, 6],
        [5, 5, 6, 6]],

       [[5, 5, 6, 6],
        [5, 5, 6, 6]]])

陣列的類別  
陣列的長度  
陣列的形狀  
陣列的維度

In [0]:
print(type(arr))
print(len(arr))
print(arr.shape)
print(arr.ndim)

<class 'numpy.ndarray'>
5
(5, 2, 4)
3


陣列形狀和維度可改變

In [0]:
arr = np.array(range(1,61))
print(arr)
print(arr.shape)
print(arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
(60,)
1


In [0]:
arr = arr.reshape(3,4,5)
print(arr)
print(arr.shape)
print(arr.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
(3, 4, 5)
3


程式名詞 vs 數學名詞  
一維陣列 aka 向量  
二維陣列 aka 矩陣  
Ｎ維陣列 aka 張量

## Part 2: numpy.ndarray 的 indexing / slicing

「連續」的 indexing / slicing  
即使 arr.ndim 等於三維，使用超過三對中括號也是可能的

In [0]:
# arr 的 整段 的 整段 的 第1個以後 的 第2個以前 的 第1個 的 第1個以後到第3個以前 的 第0個
arr[:][:][1:][:2][1][1:3][0]

array([46, 47, 48, 49, 50])

「同時」在N個不同維度 indexing / slicing  
只會使用一對中括號，和N個索引或範圍

In [0]:
print(arr[0][1][2])
print(arr[0,1,2])

8
8


無論陣列的形狀及維度為何，其實都是儲存在一段連續記憶體，N維陣列只是一維陣列用一對對中括號決定其形狀及維度  
「連續」的 slicing 只能切出一維陣列  
「同時」的 slicing 才能切出Ｎ維陣列

In [0]:
part_of_arr = arr[ :2, 1:3, -3: ]
print(part_of_arr)
print(part_of_arr.shape)
print(part_of_arr.ndim)

[[[ 8  9 10]
  [13 14 15]]

 [[28 29 30]
  [33 34 35]]]
(2, 2, 3)
3


## Part 3: pandas.DataFrame 的 indexing / slicing / selecting

用二維的 numpy.ndarray 產生 pandas.DataFrame

In [0]:
two_dim_arr = np.array(range(101,151)).reshape(5,10)
print(two_dim_arr)
df = pd.DataFrame(two_dim_arr)
df

[[101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]


0    1    2    3    4    5    6    7    8    9
0  101  102  103  104  105  106  107  108  109  110
1  111  112  113  114  115  116  117  118  119  120
2  121  122  123  124  125  126  127  128  129  130
3  131  132  133  134  135  136  137  138  139  140
4  141  142  143  144  145  146  147  148  149  150

二維陣列是先索引Row再索引Column  
而DataFrame是先索引Column再索引Row  
若DataFrame要先索引Row再索引Column，要用.loc傳入索引

In [0]:
print(two_dim_arr[2])
print(df[2])
print(df.loc[2])

[121 122 123 124 125 126 127 128 129 130]
0    103
1    113
2    123
3    133
4    143
Name: 2, dtype: int64
0    121
1    122
2    123
3    124
4    125
5    126
6    127
7    128
8    129
9    130
Name: 2, dtype: int64


In [0]:
df[ [4,2,6,9,4,4,2,6] ]

4    2    6    9    4    4    2    6
0  105  103  107  110  105  105  103  107
1  115  113  117  120  115  115  113  117
2  125  123  127  130  125  125  123  127
3  135  133  137  140  135  135  133  137
4  145  143  147  150  145  145  143  147

自訂 DataFrame 的 columns 和 index

In [0]:
print(df.columns)
print(df.index)
df.columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10']
df.index = ['R1', 'R2', 'R3', 'R4', 'R5']
print(df.columns)
print(df.index)
df

RangeIndex(start=0, stop=10, step=1)
RangeIndex(start=0, stop=5, step=1)
Index(['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10'], dtype='object')
Index(['R1', 'R2', 'R3', 'R4', 'R5'], dtype='object')


C1   C2   C3   C4   C5   C6   C7   C8   C9  C10
R1  101  102  103  104  105  106  107  108  109  110
R2  111  112  113  114  115  116  117  118  119  120
R3  121  122  123  124  125  126  127  128  129  130
R4  131  132  133  134  135  136  137  138  139  140
R5  141  142  143  144  145  146  147  148  149  150